import React from 'react';
import PropTypes from 'prop-types';
import {
	BrowserRouter as Router,
	Routes,
	Route,
	Link
} from "react-router-dom";
import BigData from './BigData';

const BDWeek1 = () => (
	<BigData>
    <div id="main">
    <section id="two">
        <div class="inner">
            <header class="major">
                <h2>Collaborative Discussion On The Data Collection Process</h2>
            </header>
            <h3>Learning Outcomes</h3>
            <ul>
                <li>Identify and manage challenges, security issues and risks, limitations, and opportunities in data wrangling.</li>
                <li>Critically analyse data wrangling problems and determine appropriate methodologies, tools, 
                    and techniques (involving preparing, cleaning, exploring, creating, optimising and evaluating big data) to solve them.</li>

            </ul>
        </div>
    </section>
    <section id="four">
        <div class="inner">
            <header class="major">
                <h3>Artefacts</h3>
            </header>
            <h4>Initial Post</h4>
        <p>In today&apos;s data-driven world, the ability to analyze large and complex datasets has become a crucial skill for businesses and organizations looking to gain a competitive edge. Big data analytics refers to the process of analyzing large volumes of data to identify patterns, trends, and insights that can be used to make informed decisions. these large amounts of data with various data sources and their formats are mostly generated by devices and sensors connected to the Internet, this concept is known as the Internet of Things (IoT).&nbsp;
        This Year About 3.5 quintillion bytes or 3.5 exabytes (10 to the power of 18) of data are created every day. (earthweb 2023).</p>
        <p>Big data exist in various formats such as;</p>
        <ul>
            <li>Structured: Organised data Ex: RDBMS</li>
            <li>Semi-Structured: Partially organised Ex: XML, JSON</li>
            <li>Unstructured: Unorganised data Ex: Audio, Test, Video files etc.</li>
        </ul>
        <p>Opportunities For Big Data Analytics</p>
        <ul>
        <li>Improved decision-making<strong>:</strong> provide insights that help businesses and organizations.</li>
        <li>Enhanced customer experience<strong>:</strong> businesses can gain a better understanding of their customer&apos;s preferences, behaviours, and needs.</li>
        <li>Increased operational efficiency<strong>:</strong> help businesses optimize their operations by identifying inefficiencies, streamlining processes, and reducing costs.</li>
        <li>Improved risk management<strong>:</strong> can help businesses identify and mitigate risks.</li>
        </ul>
        <p>Challenges And Limitations</p>
        <ul>
            <li>Privacy &amp; Security<strong>:</strong> With the collection and analysis of large volumes of data, there is a risk of sensitive information being exposed or misused. The risk of data breaches.</li>
            <li>Data quality issues<strong>:</strong> If the data is incomplete, inconsistent, or inaccurate, the insights derived from it may be flawed and lead to incorrect decision-making.</li>
            <li>Legal and ethical issues<strong>:</strong> legal and ethical issues related to data ownership, intellectual property rights, and data privacy.</li>
            <li>Scalability: Implementing and maintaining these technologies can be challenging and require significant investments.</li>
        </ul>
        

        <h4>Summary Post</h4>
        <p>The Internet of Things (IoT) offers numerous prospects for enhanced productivity and better decision-making across a variety of businesses. It does, however, have limitations that must be addressed before it can be effectively used.</p>
        <p>The benefits of IoT are in its capacity to offer valuable insights through data analysis. Interoperability problems, scalability issues, and privacy and security concerns are current limitations of IoT (Alwarafy et al., 2021). On the top of the list are security and privacy concerns. To stop data breaches and misuse, it is essential to protect people&apos;s privacy and secure sensitive data gathered by IoT devices. Adequate measures must be taken to ensure data privacy, establish clear regulations, and address ethical concerns related to consent and ownership.&nbsp;</p>
        <p>The concept of Privacy Choice is such that a system must present available privacy choices to users. It is not enough to inform the user about the use of IoT, the system must also seek the user&apos;s consent (Feng, Yao and Sadeh, 2021).</p>
        <p>Additionally, managing the massive influx of data and extracting meaningful insights require advanced analytics tools and scalable infrastructure.&nbsp;</p>
        <p>The Internet of Things holds immense promise in revolutionizing various sectors and enhancing our daily lives. By addressing the limitations, risks, and challenges associated with IoT, we can unlock its full potential and create a connected world that respects individual privacy.</p>
        <p><br/></p>
        
        <p><strong>Reference&nbsp;</strong></p>
        <p>EarthWeb. (2023). How Much Data Is Generated Every Day in 2023? (NEW Stats). Available at:&nbsp;<a href="https://earthweb.com/how-much-data-is-created-every-day">https://earthweb.com/how-much-data-is-created-every-day</a></p>
        <p>Huxley, K., 2020. Data Cleaning. In: Paul Atkinson, ed., Sage Research Methods Foundations. London: SAGE Publications Ltd. Available at: &lt;https://doi.org/10.4135/9781526421036842861&gt; [Accessed 10 May 2023].</p>
        <p>Alwarafy, A. et al. (2021) &ldquo;A survey on security and privacy issues in edge-computing-assisted internet of things,&rdquo; IEEE internet of things journal, 8(6), pp. 4004&ndash;4022. doi: 10.1109/jiot.2020.3015432.</p>
        <p>Feng, Y., Yao, Y. and Sadeh, N. (2021) &ldquo;A design space for privacy choices: Towards meaningful privacy control in the internet of things,&rdquo; in Proceedings of the 2021 CHI Conference on Human Factors in Computing Systems. New York, NY, USA: ACM.</p>
        <p>Huxley, K., 2020. Data Cleaning. In: Paul Atkinson, ed., Sage Research Methods Foundations. London: SAGE Publications Ltd. Available at: &lt;https://doi.org/10.4135/9781526421036842861&gt; [Accessed 10 May 2023].</p>
        <p><br/></p>
        

        </div>
    </section>
    <section id="two" class="spotlights">
        <section>
            <a href="generic.html" class="image">
                <img src="/assets/images/pic09.jpg" alt="" data-position="top center" />
            </a>
            <div class="content">
                <div class="inner">
                    <header class="major">
                        <h3>Reflections</h3>
                    </header>
                    <p>Participating in this fruitful discussion about the future of data scientists with my colleagues has broadened my knowledge of the critical roles and responsibilities of a data scientist, as well as the ethics and expectations of the profession.
                        To be a successful data scientist, you must have soft skills, statistical skills, mathematical skills, coding skills, and an understanding of the business domain.</p>
                    {/*<ul class="actions">*/}
                    {/*	<li><a href="generic.html" class="button">More Information here</a></li>*/}
                    {/*</ul>*/}
                </div>
            </div>
        </section>
        {/*<section>*/}
        {/*	<a href="generic.html" class="image">*/}
        {/*		<img src="/assets/images/pic10.jpg" alt="" data-position="25% 25%" />*/}
        {/*	</a>*/}
        {/*	<div class="content">*/}
        {/*		<div class="inner">*/}
        {/*			<header class="major">*/}
        {/*				<h3>Meeting Notes</h3>*/}
        {/*			</header>*/}
        {/*			<p>Notes from various meetings, as well as feedback from team members and tutors.</p>*/}
        {/*			*/}{/*<ul class="actions">*/}
        {/*			*/}{/*	<li><a href="generic.html" class="button">For specific cases, see here</a></li>*/}
        {/*			*/}{/*</ul>*/}
        {/*		</div>*/}
        {/*	</div>*/}
        {/*</section>*/}

        <section>
            <a href="generic.html" class="image">
                <img src="/assets/images/pic09.jpg" alt="" data-position="top center" />
            </a>
            <div class="content">
                <div class="inner">
                    <header class="major">
                        <h2>Professional Skills Matrix and Action Plan</h2>
                    </header>
                    <p>Skills have I gained or enhanced as a result of this module.</p>
                    <ul>
                        <li>Master Data Management Skill</li>
                        <li>Academic Writting Skill</li>
                        <li>Referencing and Citation Skill</li>
                    </ul>
                </div>
            </div>
        </section>
    </section>
    </div>
	</BigData>
);

BDWeek1.propTypes = {};

BDWeek1.defaultProps = {};

export default BDWeek1;
